#+TITLE: The Ubitarian Manifesto
#+AUTHOR: Thien-Nam Dinh
#+DATE: December 05, 2021
#+OPTIONS: toc:nil title:nil
#+LATEX_CLASS: custom
#+LATEX_HEADER: \email{thiennam.tnd@gmail.com}

#+BEGIN_abstract
I am not qualified to write manifestos.
I wrote this one.
Some of the ideas in this manifesto are new.
Some are not.
The creation of ideas is an unremarkable process.
The exchange of ideas is the most beautiful process in the universe.
#+END_abstract

#+LATEX: \maketitle
#+LATEX: \tableofcontents

* Introduction
:PROPERTIES:
:CUSTOM_ID: introduction
:END:

The situation is suboptimal.
Across the political landscape, tension continues to build over the growth of inequity, the erosion of freedom, and the failure of politics to improve the situation.
For many, the natural instinct is to blame people, to condemn those who oppress, who help to oppress, who stand by and do nothing.
That instinct is wrong.
People are not the problem.
When living in healthy environments, when connected to healthy communities, most human beings are remarkably kind, productive, and resilient[fn:humankind].
People are imperfect, but they are not the problem.

The problem is the system.
The problem is the archaic devices that we depend on to broker money, power, and information.
Our brains evolved to understand tribal communities.
Our nation evolved to govern 13 loosely connected colonies.
These are the systems that we ask to tame the unforgiving forces of economics and geopolitics.
Over the course of its impossible 246-year mission, the US state has evolved as all states do: haphazardly.
Election by election, policy by policy, good intention by good intention, the state has decayed into an incomprehensible sprawl of complexity.
The problem is the system.

We need to do better.
We need a new system to uphold the values of our society---life, liberty, and the pursuit of happiness---at the scale and ubiquity demanded by the 21st century.
In place of today's broken bureaucracy, we need a state which works as an efficient, robust machine that frees people to live the rich and remarkable lives that all are capable of living.
This manifesto describes such a machine.

** Overview
This manifesto is a concise overview of Ubitarian ideology. 
It does not attempt to justify most of the ideas, only present them as clearly as possible.
Section\nbsp[[#principles]] establishes the theoretical principles of the platform.
The platform itself, described in Sections\nbsp[[#ubi]]-[[#uif]], consists of four core policies.

- /Universal Basic Income/ provides the right to a dignified life for all individuals and restores free market dynamics to the labor economy.
- /Universal Basic Philanthropy/ creates a free and democratic market for allocating public goods.
- /Universal Capital Tax/ enforces a fair and logical tax code focusing on capital assets. 
- /Universal Information Freedom/ removes financial restrictions on information to democratize art, innovation, and knowledge.

Section\nbsp[[#other-policies]] enumerates additional supplementary policies.
Section\nbsp[[#discussion]] concludes with contextual discussion.

Ubitarianism emphasizes /idealistic/ dialog.
Due to the complexity of the modern world, it has become difficult for the public to agree on the basic facts of any sufficiently complex situation.
What passes as scientific knowledge today is more often blind trust the flawed systems that broker the information[fn:replicability].
Consequently, this manifesto primarily uses first principles to communicate ideas for a better society.
Once we have some agreement about how things /should/ be, then---and only then---we can begin to work toward it.

* Principles 
:PROPERTIES:
:CUSTOM_ID: principles
:END:

Ubitarianism is a political ideology that advocates for the creation of simple but powerful systems to maximize individual freedom.
A Ubitarian state should actively create opportunities for its people without compromising their freedom to act on them[fn:development-as-freedom].
This section introduces the two distinguishing core principles that drive the platform.

** Self-Determination
:PROPERTIES:
:CUSTOM_ID: self-determination
:END:

Self-determination is the principle of prioritizing the individual's innate tendencies to grow and contribute to society through intrinsic motivators.
Its opposite is authoritarianism, which prioritizes top-down incentives to achieve collective utilitarian outcomes through extrinsic motivators.
The principle of self-determination drives Ubitarian /theory/.

Ubitarianism rejects the traditional capitalistic and authoritarian claims that humans need heavy-handed external motivators (i.e. a sufficiently large carrot or stick) to be productive.
Instead, it assumes as a basic psychological fact that human beings are naturally creative and productive when they are in healthy environments.
This belief drives much of the rationale behind Ubitarian policies[fn:self-determination].
Rather than trying to /make/ people be productive, Ubitarian policies focus on creating the basic conditions needed to /let/ them be productive.

Ubitarianism believes that emphasizing individualism will produce better social outcomes---even for the collective.
It is skeptical of socialist policies that depend on /big/ government, as these systems are inevitably vulnerable to corruption and abuse.
Instead, Ubitarianism prefers democratic and free market systems which directly empower individuals to advocate for their own interests.

** Minimalism
:PROPERTIES:
:CUSTOM_ID: simplicity
:END:

Minimalism is the principle of taking a few simple and obvious political actions to solve /only/ the most clearly understood social issues.
Its opposite is interventionalism, which takes many reactionary incremental actions to address all social issues that emerge.
The principle of minimalism drives Ubitarian /practice/.

Ubitarianism is skeptical of /complex/ government.
In the same way that household clutter leads to pests, dust, and more clutter, complex legislation leads to corruption, unintended consequences, and more complex legislation.
This feedback loop has created today's bloated and inefficient government.
For this reason, Ubitarian minimalism prefers /simple but powerful/ systems that maximizes impact while minimizing complexity. 

A consequence of the minimalist principle is that Ubitarian only supports interventions that directly address well-understood root causes.
Most interventionalism policies today are poorly constructed half-measures deployed to solve surface-level, symptomatic issues.
Often, they win public support because they deliberately obscure their true economic costs to society.
Ubitarian minimalism calls for a conscientious effort to reject these seemingly well-intentioned half-measures.
For example, it opposes seemingly well-intentioned policies like minimum wages, corporate taxes, and green energy subsidies, which all fail to solve actual underlying problems like the broken labor market, wealth inequality, and environmental externalities.
Over time, these half-measures will cause more harm than good.
In contrast, the next sections of this document presents more effective minimalist approaches.

* Universal Basic Income
:PROPERTIES:
:CUSTOM_ID: ubi
:END:

/Universal Basic Income/ (UBI) is an unrestricted, unconditional cash income provided for all adult citizens.
The amount is substantial enough for them to sustain a healthy, dignified life in the absence of any other private income.
It enables everyone to coexist in society regardless of how economically productive they can---or even want---to be.
The amount of the UBI payment is the same for all adult citizens regardless of there they live, how much they make, or any other demographic factor.

/The purpose of UBI is to correct fundamental distortions in the labor market and to guarantee the basic right to dignified working and living conditions for everyone in society./

** Rationale
The core rationale of UBI is as follows:

- /Premise/: A prosperous state has an obligation to provide minimum welfare for citizens.
- /Premise/: A free state has an obligation to maximize the freedom of citizens.
- /Conclusion/: The state should implement UBI, which is the single form of welfare that provides the most freedom for its people.

Although this is the primary motivation, it is not the only one.
The remainder of this section outlines benefits of UBI in specific topics.

*** Welfare Systems
UBI obviates the need for the state to run most of its welfare programs.
Since UBI covers the minimum living expenses, the state can dissolve most existing programs for housing, food, and healthcare.
For individuals who face extenuating circumstances like disability or drug addiction, the state can fund smaller, targeted programs to provide additional assistance through UBP (see Section\nbsp[[#ubp]]).

UBI has the following benefits:
- /Efficiency/: Cash payouts require less logistical overhead for the state than targeted housing assistance, food stamps, and medical insurance.
- /Transparency/: Cash payouts have less need for top-down management, which in turn leaves less room for corrupt or negligent behavior by state officials.
- /Flexibility/: Individuals have a more nuanced understanding of their own needs than the state. An unrestricted cash payout has more value to individuals than an equivalent amount of restricted state services.
- /Incentivization/: UBI eliminates the perverse economic incentives of the current welfare state, which creates poverty traps that implicitly encourage the poor to stay poor[fn:the-alternative].
- /Solidarity/: UBI reduces the social stigma that exist in the current system. Since the state provides UBI to all citizens, it does not create unnecessary class divisions.

*** Labor Markets
UBI fixes a major problem with the modern labor market, which is not a free market in the traditional sense.
In a truly free market, participants must have the option to /not/ participate.
If they do not like a transaction, nobody can force them to go through with it.
When then, do so many people seem to despise their day-to-day jobs?
In the modern economy, individuals /must/ work their jobs because pawning off labor is the only way to meet their basic need for food, shelter, and healthcare.
This situation does not describe a free market.
It describes a market that is heavily distorted by an external coercive pressure.
UBI restores balance to the market by correcting for this distortion.

UBI has the following benefits:

- /Compensation/: Correcting the labor market distortion allows the pricing mechanism (i.e. wages) to more naturally incorporate the preferences of the worker. Employers would need to pay higher salaries for conventionally undesirable jobs---even unskilled jobs. Consequently, UBI obviates the need for existing policies like minimum wages and progressive taxes that imperfectly attempt to correct the current state of income inequality.
- /Working Conditions/: UBI improves working conditions by increasing competition for workers among employers. This development obviates the need for labor unions and work-place regulations.
- /Initiative/: UBI provides a safety net for workers to take on personal risk that might pay off in the future. For instance, workers could quit their jobs to go back to school or form new companies. By supporting these self-deterministic initiatives, UBI creates a more skilled labor force and a more robust economy.

*** Nonmonetary Value
The Ubitarian self-determination principle rejects the capitalistic assumption that humans /need/ financial incentives to be productive.
Instead, it assumes that, if the state provides most of their basic needs through UBI, they will naturally /want/ to find ways to contribute to their social network.
Although this type of productivity does not contribute to simplistic economic indicators like GDP, they add tremendous value to society.

UBI has the following benefits:

- /Creativity/: Amateur artists spend more time producing artwork that others can enjoy without paying for it.
- /Social Connections/: People spend more time with their families and friends, building more enriching and robust social networks.
- /Health/: People spend more time taking care of their physical and mental healthy. In addition to improve their own lives, this development reduces the strain on both the healthcare industry as well as on their own social networks.
- /Civic Engagement/: People spend more time staying informed and active in their civic lives.

** Scale
This section quantifies the potential impact of UBI for the US.
The calculation for UBI straightforward: take the number of recipients and multiple it by the payout. 
The [[https://www.census.gov/library/stories/2021/08/united-states-adult-population-grew-faster-than-nations-total-population-from-2010-to-2020.html][2020 US census]] states that the population of adults is 258.3 million.
For the payout amount, we will use the round number of $1000 per month used by presidential candidate Andrew Yang in his 2020 presidential [[https://2020.yang2020.com/][platform]].
These numbers imply a benefit of $3.1 trillion per year distributed evenly among all citizens.

This analysis may overstate the scale of UBI for the following reasons:

- UBI inflates the price of consumer goods, so $1000 per person may not be enough to cover expenses
- Adults with dependent children will need more support, which UBI may need to account for.

Conversely, this analysis may understate the scale of UBI for the following reasons:

- UBI obviates the spending currently allocated to expensive welfare programs.
- UBI increases consumer spending, which creates economic growth.

* Universal Basic Philanthropy
:PROPERTIES:
:CUSTOM_ID: ubp
:END:

/Universal Basic Philanthropy/ (UBP) is a uniform stipend provided for all citizens that they can use to fund any state-approved organizations to provide public goods.
Whereas UBI enables individuals to meet their private needs, UBP enables individuals to decide how the community meets its collective needs.
For an organization to qualify for UBP funding, it needs to satisfy the following criteria:

- It must provide nonexclusive and unreciprocated value to anyone in society.
- It must (or must reasonably expect to) be approved by at least 50% of the population.

Programs that qualify include most nonprofits, most government agencies, most art organizations, and most political parties.
Programs that do not qualify include private for-profit businesses, organizations with closed membership, and hate groups.

/The purpose of UBP is to effectively and equitably determine funding for public goods that benefit everyone in society./

** Rationale
The core rationale of UBP is as follows:

- /Premise/: People have a natural desire to engage in philanthropy, public service, and politics. 
- /Premise/: At large scales, well-maintained free market systems are more efficient and robust than top-down, bureaucratic institutions.
- /Conclusion/: UBP, which is a free market for philanthropy, public service, and politics, will be more efficient and robust than the top-down institutions that currently meet these needs.

*** Philanthropy
:PROPERTIES:
:CUSTOM_ID: philanthropy
:END:

UBP displaces traditional philanthropy by enabling more people to participate in charitable giving.
Although major philanthropists will continue to give to charitable causes, UBP is the primary way that most individuals will give.

UBI provides the following benefits:

- /Equity/: UBP allows all citizens to participate in philanthropic giving, an activity that is intrinsically rooted in privilege and affluence in the current system. It obviates the need for a charitable tax deduction, a mechanism that currently amplifies the equities in philanthropy[fn:decolonizing-wealth].
- /Deliberation/: Impulsivity drives much of traditional philanthropy. Today, many people donate when they are emotionally perturbed, for instance, at a social charity gala or after a moving advertisement. Without these perturbations, it is more rational to keep the money for themselves. Since UBP can /only/ be donated, people are able to more deliberately and rationally their donations.
- /Outreach/: UBP encourages nonprofits to shift outreach and education efforts toward the general public and away from the major donors and top-down institutions that fund them today.

*** Governance
:PROPERTIES:
:CUSTOM_ID: governance
:END:

UBP displaces bureaucracy by replacing top-down funding with grassroots funding.
This change impacts public programs like medicaid, housing, SNAP benefits and funding for parks, libraries, law enforcement, and infrastructure.

UBI provides all of the benefits mentioned in Section\nbsp[[#philanthropy]] for governance as well as the following additional benefits:

- /Efficiency/: A decentralized UBP platform replaces the need for inefficient and hierarchical bureaucratic decision-making.
- /Selection/: Grassroots organizations form more easily than top-down organizations, which means that individuals have a wider selection of organizations to support with public dollars. 
- /Diversity/: Grassroots organizations are more supportive of innovation, minority populations, and controversial issues than top-down government agencies.
- /Democracy/: UBP is a more direct way to exercise democratic power than representative government. Instead of depending on elected officials, UBP enables citizens to exercise financial power directly and immediately.

*** Activism
:PROPERTIES:
:CUSTOM_ID: Activism
:END:

UBP displaces public spending on political activism.
Using their stipend, people can fund political campaigns and lobby for causes like abortion or firearms.
UBP does not distinguish controversial activism from more non-controversial causes like education or food security.
As long as the organizations passes the 50% public support test, these causes are all equally altruistic in intent.

UBI provides all of the benefits mentioned in Section\nbsp[[#philanthropy]] and Section\nbsp[[#governance]] for activism as well as the following additional benefits:
- /Accountability/: Since everyone would have the ability to contribute more substantially to political campaigns, UBP makes politicians more accountable to everyday citizens rather than only wealthy donors.
- /Unity/: Modern political activism is a zero-sum game. Even if society agrees on most issues, the remaining contentious issues will always receive the most attention and contention. In contrast, UBP places political activism in /the same logical category/ as non-contentious activities like philanthropy and governance---people can use their UBP money to either fund a political candidate /or/ a child in need. It promotes social unity by forcing society to recognize the many values and causes that we share in common.

** Scale
This section quantifies the potential impact of UBP for the US.
The total impact is proportional to the existing government spending on welfare programs shown in Table\nbsp[[tab:spending]].
According to the [[https://www.census.gov/library/stories/2021/08/united-states-adult-population-grew-faster-than-nations-total-population-from-2010-to-2020.html][2020 US census]], the total population of the US is 331 million.
Dividing the first number by the second implies a UBP payout of $11,000 per person per year to maintain current spending on these public services.
However, not everyone will allocate their UBP stipend.
Assuming that only 50% of the 258.3 million adult population spends their UBP, which is inline with [[https://www.fairvote.org/voter_turnout#voter_turnout_101][voter turnout]], then the adjusted UBP payout is $29,000 per person per year.

#+name: tab:spending
#+CAPTION: *Breakdown of Public Spending.* Sources are documented as embedded links in each row of the first column. Spending amounts are shown as billion USD annually.
|-------------------------------+------+----------|
|                               | Year | Spending |
|-------------------------------+------+----------|
| [[https://www.usgovernmentspending.com/welfare_spending][Welfare]]                       | 2021 |    2,319 |
| [[https://educationdata.org/public-education-spending-statistics][Public Education]]              | 2020 |      734 |
| [[https://ncses.nsf.gov/pubs/nsf21324][Public Research & Development]] | 2019 |      171 |
| [[https://www.americansforthearts.org/sites/default/files/aep5/PDF_Files/NationalFindings_StatisticalReport.pdf][Nonprofit Arts]]                | 2017 |      166 |
| [[https://usafacts.org/articles/police-departments-explained/][Law Enforcement]]               | 2017 |      193 |
| [[https://usafacts.org/state-of-the-union/transportation-infrastructure/][Infrastructure]]                | 2018 |      169 |
|-------------------------------+------+----------|
| Total                         |      |    3,752 |
|-------------------------------+------+----------|
#+TBLFM: @>$3=vsum(@2..@-1)

This analysis may overstate the scale of UBP for the following reasons:

- If UBI were also implemented, then it would obviate much of the welfare budget listed in Table\nbsp[[tab:spending]], meaning that the UBP payout would not need to be as high.
- Even with UBP, the state will likely want to retain some centrally allocated funding for certain programs.

Conversely, this analysis may understate the scale of UBP for the following reasons:

- Table\nbsp[[tab:spending]] is non-comprehensive and does not cover many other viable uses of UBP such as funding for parks, libraries, religion, political campaigning, nonprofit lobbying, and many others.
- If UFI were implemented, UBP becomes an important source of funding for creative arts and research & development. The state should increase the UBP payout accordingly.

* Universal Capital Tax
:PROPERTIES:
:CUSTOM_ID: uct
:END:

/Universal Capital Tax/ (UCT) is a tax on all capital owned within the state's jurisdiction that is proportional to the financial value of each asset.
Examples of capital assets include the following: equity in public and private companies, bonds and other forms of debt, private real estate, cash currency, cryptocurrency, commodities like gold or oil, and nonfungible goods like artwork. 

Unlike most existing forms of taxes, UCT taxes capital rather than individuals.
In other words, it does not distinguish between whether the taxpayer is a citizen or not, how much they make, where they live, or any other factor.
It indiscriminately levies a tax against /whomever/ owns an asset that belongs in the state's jurisdiction.
If the owner of an asset fails to pay the tax, then they forfeit their right to legally own the asset, which leaves it in possession of the state.
UCT obviates most existing forms of taxes like income, corporate, and capital gains taxes.

/The purpose of UCT is to rationally and equitably generate funding for public goods that benefit everyone in society./

** Rationale
The core rationale of UCT is as follows:

- /Premise/: Flat income taxes are unfair because it punishes people in poverty. Progressive income taxes are unfair because it punishes valuable labor. 
- /Premise/: Strong public institutions exist to build and maintain private capital. In turn, these institutions require public money to build and maintain. 
- /Conclusion/: The most fair tax policy is to tax capital instead of individuals.

Although this is the primary motivation, it is not the only one.
The remainder of this section outlines benefits of UCT in specific topics.

*** Tax Collection
Today, the state levies taxes on /transactions/, for instance, when a person receives a paycheck (income tax), when they make a purchase (sales tax), or when they sell a financial asset for a profit (capital gains tax).
In other words, the state taxes wealth "on the move," i.e. whenever wealth changes hands.
In contrast, UCT taxes wealth "at rest," i.e. taxing any asset that exists within the jurisdiction on a regular interval (e.g. every year on April 15).

UCT has the following benefits:

- /Incentivization/: In the current system, high income taxes adversely disincentivize labor, sales taxes disincentivize consumption, and capital gains taxes disincentivize trade. Since UCT only taxes wealth "at rest", it does not penalize economic activity. 
- /Transparency/: Since the identify of the taxpayer doesn't matter, UCT eliminates any incentive for them to set up convoluted off-shore tax havens.
- /Information/: In the same way that transactional taxes attract a massive industry around accounting and auditing, UCT will attract an industry around how to correctly price assets for tax purposes. Although this information requires some overhead to maintain, the output would arguably provide more useful economic information than the current system.

*** Wealth Distribution
UCT obviates wealth redistribution mechanisms such as progressive income, inheritance taxes, and corporate taxes.
Many left-leaning views promote taxing the rich as a moral obligation of the state.
Although Ubitarianism does not share these normative moral views, UCT does happen to lead to far more equitable outcomes as a simple matter of mathematical fairness.

UCT has the following benefits:

- /Scale/: As shown in Section\nbsp[[#utc-scale]], UCT fairly distributes wealth at a far more aggressive scale than progressive income taxes.
- /Legitimacy/: UCT applies exactly the same way to all individuals without making any normative judgments about income or wealth accumulation. As a result, it is less divisive and difficult to oppose on a rational basis.
- /Objectivity/: The major philosophical issue with morally normative wealth redistribution is that society must answer the following question: how equal is equal enough? UCT sidesteps that question entirely because it does not depend on normative morals.
- /Robustness/: Most wealth redistribution mechanisms like progressive income tax, inheritance taxes, and corporate taxes only address current issues with wealth accumulation---they do not address /historical/ issues that have led today's enormous wealth inequality. In addition, they are fundamentally reactionary---if /future/ issues arise, we will need to adjust tax rates and invent new taxes in response. In contrast, UCT is an inherently robust mechanism that accounts for both historical and future wealth accumulation, leading to a more stable wealth distribution over time. 

** Scale
:PROPERTIES:
:CUSTOM_ID: utc-scale
:END:

This section quantifies the potential impact of UCT for the US.
At the end of 2020, the [[https://www.federalreserve.gov/releases/z1/dataviz/dfa/distribute/table][estimated wealth]] of US households was $123 trillion.
In order to match the 2020 federal [[https://www.cbo.gov/publication/57170][budget]] revenue of $3.4 trillion, the state would need to tax assets at 2.8% of their value under UCT.
In this analysis, we deliberately keep the total revenue constant.

#+name: tab:distribution
#+CAPTION: *Traditional Tax vs UCT for Households.* Sources for tncome and wealth data is documented as embedded links in the column headers. Current tax amounts (Current*) are estimated by combining an online [[https://www.nerdwallet.com/taxes/tax-calculator][tax calculator]] (single filing, no deductions) and the official federal revenue [[https://www.cbo.gov/publication/57170][breakdown]]. We make the simple assumption that the burden of non-income taxes (e.g. payroll, capital gains, corporate) are passed on to individuals proportionally to their income. The last row considers the estimated [[https://fortune.com/2021/07/30/jeff-bezos-net-worth-amazon-stock-amzn-earnings-update/][net worth]] of Jeff Bezos as of July 2021. All amounts are shown as thousand USD annually.
|-------+--------+-------------+-----------+-----------|
|     % | [[https://dqydj.com/average-median-top-household-income-percentiles/][Income]] |      [[https://dqydj.com/average-median-top-net-worth-percentiles/][Wealth]] |  Current* |       UCT |
|-------+--------+-------------+-----------+-----------|
|     5 |     10 |         -18 |         0 |         0 |
|    25 |     34 |          12 |         5 |         0 |
|-------+--------+-------------+-----------+-----------|
|    50 |     68 |         121 |        17 |         3 |
|-------+--------+-------------+-----------+-----------|
|    75 |    122 |         403 |        42 |        11 |
|    95 |    270 |       2,584 |       138 |        71 |
|    99 |    531 |      11,099 |       332 |       305 |
|-------+--------+-------------+-----------+-----------|
| Bezos |     82 | 198,000,000 | *Unclear* | 5,460,000 |
|-------+--------+-------------+-----------+-----------|

The primary impact of UCT is to fairly redistribute the tax burden among the population based on wealth.
Table\nbsp[[tab:distribution]] compares the tax burden under the existing system against the hypothetical tax burden under UCT.
Based on these rough estimates, UTC lowers the tax burden of the bottom 99% of US households.
One illustrative data point is the tax burden of the median household, which shifts from $17,000 per year under the existing tax code to $3,000 per year under UCT.
Only the top 1% would see a tax increase under UCT.

This analysis may overstate the scale of UCT for the following reasons:

- The tax burden decreases the value of assets.
- Some individuals will move some assets off-shore.
- If implemented, UBI and UBP would increase the state's spending, which would require a higher UCT tax rate to compensate.

Conversely, this analysis may understate the scale of UCT for the following reasons:

- Since UCT allows for the removal of all other taxes, the value of assets would increase. For instance, stocks would gain value because the underlying corporation, which no longer has to account for payroll, income, or sales taxes, would be more profitable.
- If Ubitarian policies are effectively implemented, they should increase the wealth of the country overall, leading to a larger tax base.

* Universal Information Freedom
:PROPERTIES:
:CUSTOM_ID: uif
:END:

/Universal Information Freedom/ (UIF) is a policy which removes all legal restrictions on sharing of information for financial reasons.
Applied to current US system, UIF entails the removal of all patent law, copyright law, trade secret protections, and restrictions against insider trading.
The result is that anyone would have the right to use, reproduce, and build upon any technology, work of art, or market information without repercussions.

/The purpose of UIF is to democratize culture influence and collaboratively propogate information in a way that will benefit everyone in society./

** Rationale
The core rationale of UIF is as follows:

- /Premise/: Physical goods are naturally scarce. The concept of physical property makes it easier to equitably and efficiently distribute physical goods.
- /Premise/: Information is naturally abundant. The concept of intellectual property makes it harder to equitably and efficiently distribute information.
- /Conclusion/: Intellectual property is an unnatural and unnecessary degenerate capitalistic construct.

Although this is the primary motivation, it is not the only one.
The remainder of this section outlines benefits of UIF in specific topics.

*** Technology
The dissolution of patent and trade secret protection most directly impacts technological research and development (R&D).
Today, there are two primary justifications for these laws:

1. /Ethical/: Individuals have a right to profit from an invention if they conceptualize it first.
2. /Practical/: Patent and trade secrets are beneficial for society because they are necessary to encourage technological progress.

Ubitarianism rejects the validity of justification /1./, which is an unsubstantiated social construct.
Although it is ethical to assign proper credit to inventors, there is no natural reason to provide them with exclusive rights when all inventions depend on other inventions.
Meanwhile, justification /2./ an inefficient and convoluted way to incentivize high-quality technological progress.
A better way is for the state to simply pay a fixed reward new for inventions so that distributors can immediately put them into production.
UBP would be a viable method to allocate funding for these rewards.
For instance, the state might set up a nonprofit which offers a substantial UBP-funded reward to the first private company that invents---and publishes---a cure for some specific disease.

UIF (combined with UBP incentives for inventors) has the following benefits:

- /Prioritization/: UIF/UBP prioritizes technology, especially medicine, that maximizes public need rather than private profits.
- /Proliferation/: Once an invention is made public, then other inventors can more quickly build off of it to produce better inventions.
- /Ethics/: Since corporations would no long have artificial monopolies, they would not have to make artificial ethical decisions about how to exercise their monopoly. For instance, pharmaceutical companies that manufacture life-saving drugs would simply compete to sell the them as inexpensively as possible.
- /Motivation/: Since UIF allows all technological progress to benefit the public, it provides more intrinsic, altruistic motivation for talented individuals to pursue research careers.
- /Efficiency/: UIF eliminates legal fees associated with the maintenance and protection of patents and trade secrets.

*** Art
The dissolution of copyright law most directly impacts art and culture.
The term "art" in this section refers to any creative piece of information such as the image on a painting, the notes of a song, the bytes that encode a blockbuster film, the software of a video game, or the words of a novel, or likeness of a professional athlete.
Today, there are two primary justifications for copyright law:

1. /Ethical/: Artists have a right to profit from their art if they are the ones who created it.
2. /Practical/: Patents are beneficial for society because they are necessary to encourage artistic creation.

Ubitarianism rejects the validity of justification /1./, which is an unsubstantiated social construct.
Although it is ethical to assign proper credit to artists, there is no natural reason to provide them with exclusive rights when all art draws inspiration from other art.
Meanwhile, justification /2./ is an inefficient and convoluted way to incentivize high-quality art.
If the state wants to facilitate higher artistic creation, it should begin by covering living expenses for artists.
UBI is the most effective way to accomplish this goal.
If the state wants to fund larger projects and reward highly influential artists, then it should directly provide money for their public creation. 
UBP is the most effective way to accomplish this goal.
Finally, artists have other ways to earn money that do not depend on the state:

- /Crowdfunding/. People have an inherent desire to support artists for altruistic reasons. The [[https://link.springer.com/content/pdf/10.1007/s10824-020-09381-5.pdf][success]] of platforms like GoFundMe and Patreon is proof of this phenomenon.
- /Advances/. Good artists can profit from promises to make future art. Individuals and businesses that benefit from art will pay them fee-for-services in advanced for specific artwork.
- /Cultural Influence/. Popular artists can profit off of their celebrity status. In the music industry, [[https://www.digitalmusicnews.com/2017/07/17/artists-touring-revenue/][data]] indicates that many popular artists already profit more in-person concerts than selling their music directly.

UIF (combined with UBI and UBP incentives for artists) has the following benefits:

- /Democratization/: By removing the legal mechanisms that artificially prop up large entertainment conglomerates, UIF creates more space for /local/ and culturally /diverse/ forms of art to thrive.
- /Collaboration/: UIF removes legal barriers to artistic collaboration and inspiration, a development especially benefits genres like music sampling, pop art, and fan-fiction.
- /Accessiblility/: UIF increases the proliferation of art making the cultural education and enrichment that comes with it accessible to everyone for free.
- /Virtuousness/: Under UIF, the creation of art is driven by artistic motivation and less by economic incentives[fn:coase]. The result is that dehumanizing and addictive media like pornography and video games would be less profitable.
- /Efficiency/: UIF eliminates legal fees associated with the maintenance and protection of copyright.

*** Markets
The dissolution of insider trading laws most directly impacts financial markets.
Today, the justification is practical: proponents believe that we need to create an even playing field in financial markets in order to protect small outsider traders.
However, this justification reflects an outdated, fanciful view of entrepreneurship
The reality is that these laws overwhelmingly benefit large corporations and law firms.

UIF has the following benefits:

- /Proliferation/: Removing insider trading laws allows markets to do what they do best: quickly propagate economic information at scale. The price of shares will more quickly alerts the public to scandals, technological breakthroughs, and sales results that better reflect the true value of a company.
- /Transparency/: Even with insider trading laws, outsider traders (e.g. amateur day-traders) are already at a disadvantage. UIF removes the pretense of fairness.
- /Efficiency/: UIF eliminates legal fees associated with the maintenance and protection of insider trading law.

** Scale
This section quantifies the potential impact of UIF for the US.
The removal of patent and trade secret law would most directly affect private research & development, which the National Science Foundation [[https://ncses.nsf.gov/pubs/nsf21324][estimated]] to be $486 billion in 2019.
The removal of copyright law would most directly affect the creative arts industries, which we estimate to be $552 billion in Table\nbsp[[tab:creative]].
Finally, the removal of insider trading laws would affect all publicly traded stocks, which one source [[https://siblisresearch.com/data/us-stock-market-value/][estimated]] to be $48 trillion in 2021.

#+name: tab:creative
#+CAPTION: *Revenue of Creative Industries.* All data is US-only except licensed merchandise, which includes both US and Canadian revenue. Revenue amounts are shown as billion USD annually.
|----------------------+------+---------|
|                      | Year | Revenue |
|----------------------+------+---------|
| [[https://www.americansforthearts.org/sites/default/files/aep5/PDF_Files/NationalFindings_StatisticalReport.pdf][Nonprofit Arts]]       | 2017 |     166 |
| [[https://www.hollywoodreporter.com/business/business-news/licensed-merchandise-sales-hit-2517b-903029/][Licensed Merchandise]] | 2015 |     146 |
| [[https://www.selectusa.gov/media-entertainment-industry-united-states][Television]]           | 2019 |      91 |
| [[https://www.selectusa.gov/media-entertainment-industry-united-states][Book]]                 | 2018 |      38 |
| [[https://www.selectusa.gov/media-entertainment-industry-united-states][Video Games]]          | 2019 |      26 |
| [[https://www.nexttv.com/news/us-digital-video-revenue-surpassed-dollar265-billion-in-2020-deg-says][Video Streaming]]      | 2020 |      26 |
| [[https://www.selectusa.gov/media-entertainment-industry-united-states][Music]]                | 2019 |      22 |
| [[https://qz.com/1309527/porn-could-have-a-bigger-economic-influence-on-the-us-than-netflix/][Pornography]]          | 2018 |      15 |
| [[https://www.selectusa.gov/media-entertainment-industry-united-states][Cinema]]               | 2019 |      11 |
| [[https://apnews.com/article/newspapers-business-arts-and-entertainment-ecdff2581db22fa4c627c8bfd8b48eef][Newspaper]]            | 2020 |      11 |
|----------------------+------+---------|
| Total                |      |     552 |
|----------------------+------+---------|
#+TBLFM: @>$3=vsum(@2..@-1)

This analysis may overstate the scale of UIF for the following reasons:

- Patents only motivate some of the investment into research & development. Even without patent law, companies would still compete to bring new products to the market.
- Copyright only accounts for some of the value in the creative arts industry. Access to digital platforms, in-person ticket sales, and other sales accounts for much of this revenue.

Conversely, this analysis may understate the scale of UIF for the following reasons:

- Funding for public R&D under UIF is more impactful than equivalent funding for private R&D because it provides technological benefits for a larger population.
- Finding for intrinsically-motivated art under UIF is more impactful than equivalent funding for financially-motivated art because provides cultural benefits for a larger population.
- Table\nbsp[[tab:creative]] only accounts for some industries that directly benefit from copyright law; there are many others which indirectly benefit.

* Supplementary Policies
:PROPERTIES:
:CUSTOM_ID: other-policies
:END:

This appendix lists assorted secondary policies that complement the four core policies of the Ubitarianism platform.
They aim to address one-off issues that are not covered by the core platform.
Many of them are well-established in the political discourse.
None have been implemented at scale.

** Pigouvian/Carbon Tax
/Pigouvian Tax/ is a tax on a negative externality created by an entity that is proportional to the social damage caused by the entity.
The quintessential---and perhaps most important---example is a carbon tax on entities that produce greenhouse gases.
The purpose of this policy is take precisely the most direct action to limit externalities.
It obviates top-down, adhoc mechanisms like green energy subsidies and regulations.

** Ranked Choice Voting
/Ranked Choice Voting/ is an election system where voters rank candidates according to relative preferences.
The purpose of this policy is to encourage---using mathematically provable game-theory---a less divisive, non-partisan political landscape consisting of many different political parties.
It replaces the standard run-off election system that naturally gravitates toward contentious two-party politics.

** Immigration Tax
/Immigration Tax/ is a tax levied on new citizens of a country that is enforced for some period of time after they receive their citizenship.
The purpose of this policy is to control the flow of immigration in the most fair way.
It improves the current immigration policy which stifles legal immigration and rewards illegal immigration.

** Limited Legislation
/Limited Legislation/ is a mechanism to limit the length of allowable legislation over some period of time as measured by word count.
The purpose of this policy is to directly limit the complexity of legislative policy.
It counteracts the natural incentives in representative government for politicians to further their own careers by adding to legislative bloat.

** One Child, One Vote
/One Child, One Vote/ is a policy which allows guardians of minors to allocate an extra vote during all democratic elections.
The purpose of this policy is to correct the under-representation of children and families in government policy.
It forces the state to more accurately consider the needs of the next generation in both immediate governance as well as long-term policy-making.

* Discussion
:PROPERTIES:
:CUSTOM_ID: discussion
:END:

This section provides closing discussion to elaborate on the place of Ubitarianism relative to competing ideologies and to the existing establishment.

** Other Ideologies
Ubitarianism has the following commonalities and differences with other popular ideologies.

*** Socialism
Socialism is an ideology that calls for the government to control the production, distribution, and exchange of economic goods.
Like Ubitarianism, it recognizes a strong need for more economic equality, better social safety nets, and increased public spending.
However, most Socialist policies like /Medicare for All/ and /The Green New Deal/ conflict with Ubitarian minimalism.
Ubitarianism opposes these complex authoritarian policies in favor of more free-market policies like UBI and carbon taxing, respectively.
Furthermore, it opposes divisive and interventionalist far-left ideas like racial reparations and higher taxes for the wealthy.
UCT achieves much of the same benefits under a more fair and logical framework.

*** Libertarianism
Libertarianism is an ideology that seeks to maximize personal choice by removing all but the most strictly necessary government interventions.
Like Ubitarianism, it aims to increase the role of free markets and decrease the role of top-down decision-making.
However, Ubitarianism rejects the Libertarian hypothesis that society will thrive if the state does nothing at all.
Naive Laissez-faire policy does /not/ lead to optimal market conditions.
UBI is needed to create a truly free labor market and UBP is needed to create a well-functioning market for public goods.
Taxation through UCT is /not/ theft because the social construct of private property would be impossible without the state.

*** Moderatism
Moderatism is an ideology that avoids extreme left or right positions in favor of pragmatic compromises that satisfy both sides.
Like Ubitarianism, it lies in the middle of the left/right economic spectrum.
However, Ubitarianism rejects the moderatist assumption that incremental policies are inherently beneficial.
Centuries of moderate compromises are precisely the cause of the complexity, inconsistency, and bloat of the modern state.
Consequently, Ubitarianism maintains principled and uncompromising views on all issues.

** Path Forward
Although the Ubitarian platform may seem distant and utopian, it is surprisingly achievable and realistic.
The main logistical challenge is to set up the infrastructure:

- A money distribution system for UBI,
- A money distribution system and nonprofit vetting system for UBP
- An asset tax collection system for UCT

Once a minimal infrastructure is in place, each of the four core policies and most of the supplementary policies are /tunable/.
Policy-makers can decide to fully or partially implement each individual policy by simply adjusting a few financial variables:

- The amount of money in the UBI payout
- The amount of money in the UBP payout
- The tax percentage of UCT
- The time to phase out patent and copyright protections for UIF

This transitional tuning allows policy-makers to stress-test the system and monitor the effects on the economy.
In this way, society can transition to a Ubitarian state as quickly or as slowly as it needs to.
  
** Challenges
The two main barriers to adoption are /infrastructure/ and /ethos/.
Ubitarian policies require a level of technical and organizational sophistication that is within reach of modern society.
From an organizational standpoint, the state would need to establish legislation and executive agencies to facilitate the large-scale financial transfers described in this document.
From a technological standpoint, Ubitarian policies would benefit from advances in information[fn:semantic-web], financial[fn:bitcoin] and identification systems[fn:ssi].
It is possible to make these systems to be secure, confidential, and efficient.

The more difficult challenge is ethos.
Perhaps the greatest achievement of modern society is to establish within its people a precious handful of shared beliefs like the value of human life, equal representation, freedom of speech, and the rule of law.
Although people still debate the specific implications of these values, few people seriously question their core legitimacy.
The most important challenge for Ubitarianism is to add the following two new principles to the American ethos:

- /Self-Determination/: Society /must/ believe that all people have a natural desire to be productive members of their community
- /Minimalism/: Society /must/ believe that complexity---not money---is the root of all systemic evil

If society someday embraces these principles, it will also embrace the logic they entail.

** Conclusion
:PROPERTIES:
:CUSTOM_ID: conclusion
:END:

The situation is suboptimal.
But it is not unsalvageable.
People are good.
The system still functions.
When good people are free to think, talk, and act in a functional system, the right solutions will win.
This document describes such a solution.

The Ubitarian state is a machine that controls the forces of money, power, and information for the ultimate benefit of its people.
Whether by this name or any other, we will build this machine---the only question that remains is /when/.
The situation is suboptimal.
Now is the perfect time to begin.

#+LATEX: \bibliographystyle{abbrv}
#+LATEX: \bibliography{references.bib}

* Footnotes
[fn:humankind] /Humankind/ is a book that describes the basic decency of the human species and argues for society to move toward a more positive outlook of humanity[[cite:bregman2020humankind]].
[fn:development-as-freedom] /Development as Freedom/ is a book that argues for the active creation of personal freedoms as the goal for developing states\nbsp[[cite:sen2014development]].
[fn:the-alternative] /The Alternative/ is a book that addresses erosion of self-determination and pride that is resulting from the current divisize nature of charitable institutions\nbsp[[cite:miller2017alternative]]
[fn:self-determination] Self-determination is also a well-studied macro psychological theory\nbsp[[cite:deci2008self]].
[fn:decolonizing-wealth] /Decolonizing Wealth/ is a book that addresses the cultural and economic inequities of traditional philanthropy\nbsp[[cite:villanueva2021decolonizing]].
[fn:sympathy] In a seminal paper "Sympathy and callousness", researchers suggest that emotional anecdotes are more powerful than logical statistics for procuring charitable donations\nbsp[[cite:small2007sympathy]]
[fn:coase] The landmark paper known as "Coase's Penguin" elaborates on the phenomenon of open-sourced software and other forms of crowd-sourcing that defy simplistic economic logic\nbsp[[cite:benkler2002coase]]
[fn:man-economy-state] /Man, Economy, and State/ is a seminal work of Libertarian ideology that explains the merits of the free market\nbsp[[cite:rothbard2004man]].
[fn:replicability] A seminal meta-study published in 2015 drew attention to an ongoing problem with scientific research\nbsp[[cite:open2015estimating]].
[fn:semantic-web] The Semantic Web is a growing technology that aims to improve the sharing of semantically meaningful statements of truth on the Internet\nbsp[[cite:berners2001semantic]].
[fn:bitcoin] Blockchain technology like Bitcoin aims to improve accessibility, security, and transparency of digital finance\nbsp[[cite:nakamoto2008bitcoin]].
[fn:ssi] Self-Sovereign Identity is a growing movement to decentralize control of digital identification information\nbsp[[cite:allen2016path]].
